name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore ./src/SilkierQuartz/SilkierQuartz.csproj
    - name: Build
      run: dotnet build  ./src/SilkierQuartz/SilkierQuartz.csproj  --configuration Release  
    - name: Test
      run: dotnet test ./test/SilkierQuartz.Test.csproj  --verbosity normal
